apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "tf-etcd-cluster"
  namespace: system
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  pod:
    etcdEnv:
    - name: ETCD_AUTO_COMPACTION_RETENTION
      value: "24"
    - name: ETCD_DEBUG
      value: "false"
  version: "v3.5.7"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-tribefire
  namespace: system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
  sessionAffinity: None
  type: ClusterIP
