@Library('main') _
runCiPipeline(
	jenkinsfile: this,
	projectBaseName: 'core',
	periodicRunFrequency: 'frenzy',
	ciNotificationChannel: '#pd-cxz-cicd',
	integrationTests : [
		[
			artifactName: 'tribefire-services-integration-test',
			skip: false,
			runtimeCreationTimeout: 75, // reduced timeout, since we know deployment is supposed to be quite fast
			autoGeneratedDatabases: [
				[
					key: 'services'
				]
			],
			componentsSettings: [
				[
					name: 'tribefire-master',
					env: [
						TRIBEFIRE_CORTEX_TESTING_MAIN_QA_CARTRIDGE_URL: 'http://__RUNTIME_NAME__-main-qa-cartridge:8080/',
						TRIBEFIRE_CORTEX_SERVICES_PROCESS_ENGINE_EXAMPLE_CARTRIDGE_URL: 'http://__RUNTIME_NAME__-pe-example-cartridge:8080/',
						INTEGRATION_TEST_DB_NAME: '__AUTO_GENERATED_DATABASE_services_NAME__',
						INTEGRATION_TEST_DB_HOST: '__AUTO_GENERATED_DATABASE_services_HOST__',
						INTEGRATION_TEST_DB_USER: '__AUTO_GENERATED_DATABASE_services_USER__',
						INTEGRATION_TEST_DB_PASSWORD: '__AUTO_GENERATED_DATABASE_services_PASSWORD__',
					]
				]
			]
		],
		[
			artifactName: 'parallel-test-execution-example-integration-test',
			skip: true
		]

	]
)
