!com.braintribe.devrock.model.repository.RepositoryConfiguration {        
    localRepositoryPath: "${env.repo}",    
    repositories: [
       !com.braintribe.devrock.model.repository.MavenHttpRepository {
           name: "archive-updating",           
           url: "http://localhost:${env.port}/archive-updating",
           updateable: true
       },
       !com.braintribe.devrock.model.repository.MavenHttpRepository {
           name: "archive-implicitly-updating",           
           url: "http://localhost:${env.port}/archive-implicitly-updating",           
       },
       !com.braintribe.devrock.model.repository.MavenHttpRepository {
           name: "archive-non-updating",           
           url: "http://localhost:${env.port}/archive-non-updating",
           updateable: false
       },
   ],
}            