// ============================================================================
// Copyright BRAINTRIBE TECHNOLOGY GMBH, Austria, 2002-2022
// 
// This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License along with this library; See http://www.gnu.org/licenses/.
// ============================================================================
package com.braintribe.model.processing.query.parser.impl.listener;

import java.util.ArrayList;
import java.util.List;

import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.AndPredicateContext;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.BooleanAtomicExpressionContext;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.BooleanValueExpressionContext;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.NegationPredicateContext;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.OrPredicateContext;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.ParenthesizedBooleanValueExpressionContext;
import com.braintribe.model.processing.query.parser.impl.context.ConditionCustomContext;
import com.braintribe.model.processing.query.parser.impl.context.ObjectCustomContext;

public abstract class GmqlBooleanConditionParserListener extends GmqlLiteralParserListener {

	@Override
	public void exitBooleanValueExpression(BooleanValueExpressionContext ctx) {
		setValue(ctx, takeValue(ctx.orPredicate()));
	}

	@Override
	public void exitOrPredicate(OrPredicateContext ctx) {
		List<AndPredicateContext> andPredicateList = ctx.andPredicate();
		if (andPredicateList.size() > 1) {
			List<Object> operands = new ArrayList<Object>();
			while (!andPredicateList.isEmpty()) {
				Object currentObject = takeValue(andPredicateList.remove(0)).cast().getReturnValue();
				operands.add(currentObject);
			}
			setValue(ctx, new ConditionCustomContext($.disjunction(operands)));

		} else {
			setValue(ctx, new ObjectCustomContext(takeValue(ctx.andPredicate(0)).getReturnValue()));
		}
	}

	@Override
	public void exitAndPredicate(AndPredicateContext ctx) {

		List<NegationPredicateContext> negationPredicateList = ctx.negationPredicate();
		if (negationPredicateList.size() > 1) {
			List<Object> operands = new ArrayList<Object>();
			while (!negationPredicateList.isEmpty()) {
				Object currentObject = takeValue(negationPredicateList.remove(0)).cast().getReturnValue();
				operands.add(currentObject);
			}
			setValue(ctx, new ConditionCustomContext($.conjunction(operands)));

		} else {
			setValue(ctx, new ObjectCustomContext(takeValue(ctx.negationPredicate(0)).getReturnValue()));
		}
	}

	@Override
	public void exitNegationPredicate(NegationPredicateContext ctx) {
		if (ctx.Not() != null) {
			setValue(ctx, new ConditionCustomContext($.negation(takeValue(ctx.booleanAtomicExpression()).getReturnValue())));
		} else {
			setValue(ctx, takeValue(ctx.booleanAtomicExpression()));
		}
	}

	@Override
	public void exitBooleanAtomicExpression(BooleanAtomicExpressionContext ctx) {
		propagateChildResult(ctx);
	}

	@Override
	public void exitParenthesizedBooleanValueExpression(ParenthesizedBooleanValueExpressionContext ctx) {
		setValue(ctx, takeValue(ctx.booleanValueExpression()));
	}

}
