version: "2"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
       - ./docker-entrypoint-es.sh:/docker-entrypoint-es.sh
    entrypoint: /docker-entrypoint-es.sh
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.3.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge