apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tracing
  namespace: observability
spec:
  strategy: production
  collector:
    maxReplicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    type: cassandra
    options:
      cassandra:
        servers: cassandra
        keyspace: jaeger_v1_datacenter3
    cassandraCreateSchema:
      enabled: true