---
  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: "Test Swagger Import"
    description: "This is description"
    termsOfService: "http://swagger.io/terms/"
    contact: 
      name: "Cortex Team"
    license: 
      name: "MIT"
  host: "tribefire-services.swagger.io"
  basePath: "/api"
  schemes: 
    - "http"
  consumes: 
    - "application/json"
  produces: 
    - "application/json"
  paths: 
    /tasks: 
      x-summary: Tasks
      x-description: Tasks path used for testing.
      get: 
        description: "Returns all tasks from the system that the user has access to"
        produces: 
          - "application/json"
        responses: 
          "200":
            description: "A list of tasks."
            schema: 
              type: "array"
              items: 
                $ref: "#/definitions/Task"
  definitions: 
    Task: 
      type: "object"
      required: 
        - "id"
        - "name"
      properties: 
        id: 
          type: "integer"
          format: "int64"
        name: 
          type: "string"
        tag: 
          type: "string"
        enumType:
          type: string
          enum:
            - enumValue1
            - enumValue2
            - enumValue3
      x-summary: Tasks
      x-description: Tasks path used for testing.
      example: 

