  !com.braintribe.devrock.model.repository.RepositoryConfiguration {        
    localRepositoryPath: "cache",
    repositories: [
        !com.braintribe.devrock.model.repository.MavenHttpRepository {
            name: "dev-env-repo",
            user: "repo-user",
            password: "repo-pwd",
            url: "http://repo/contents",
        },
    ],
  }            