apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd-restore-operator
  name: etcd-restore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-backup-operator
  template:
    metadata:
      labels:
        app: etcd-restore-operator
    spec:
      containers:
        - name: etcd-restore-operator
          image: ghcr.io/on2itsecurity/etcd-operator:v1.2.2@sha256:11d9170aa5df05f492e5f7edf3d369d0bc81527cedffaa712023b3abd5959a38
          command:
          - etcd-restore-operator
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
