<footer>
        <span class='feedback'><a href="https://jira.braintribe.com/secure/CreateIssue!default.jspa?selectedProjectId=12501&amp;issuetype=3">Feedback</a></span>
        <div class=logo><a href="https://www.braintribe.com"><img src="${resDir}braintribe-black-32x152.png"/></a></div>
        <div class=copyright> 
            ©2019 Braintribe. All rights reserved. <br/>
            <span class='builtwith'>Built with jinni#${jinniVersion!"<unknown version>"} at ${.now?string.long}</span>
        </div>
</footer>